---
title: "DE ggplot2 plot volcano"
output:
  pdf_document: default
  html_document: default
---

#1. Input Data

```{r}
load(file = '~/Mithrandir.training/R.data/OutputData/Input_DE_Data.rdata')
```

#2. Plot

ggplot软件思路：

1. 图层；
2. 映射；
3. 自定义标度；
4. 主题。

##快速入门

```{r, fig.height=6, fig.width=8, dpi=1800}
# 快速入门
library(ggplot2)
library(ggsci)

# 创建文件
# pdf(file = 'DE_volcano.pdf')

# 创建画布
ggplot(
  data = DE_KID_S1_vs_BLO_S1_Result, aes(x = logFC, y = -log10(PValue))
) + 
  
  # 添加散点图
  geom_point(
    
    # 映射颜色到direction
    aes(color = direction)) +
  
  # ggsci改变颜色标度
  scale_color_aaas() +

  # 改变主题
  theme_bw() 
  
#输出pdf
# dev.off()

```

##美化设计

```{r, fig.height=5, fig.width=6, dpi=1800}

#美化设计


##-------------------------------------------------------------------------

library(ggplot2)
library(ggsci)
library(tidyverse)
#添加标签软件包
library(ggrepel)

#创建文件
#pdf(file = 'DE_volcano.pdf')

##-------------------------------------------------------------------------

#创建调色板
my_palette <- c('#E64B35FF', '#999999', '#4DBBD5FF', 'red')

#按照direction排序分配颜色
##更改原始数据类型为factor
DE_KID_S1_vs_BLO_S1_Result <- mutate(
  DE_KID_S1_vs_BLO_S1_Result,
  direction = 
    factor(direction, levels = c('up', 'ns', 'down')))

#筛选条件标出标签
top_de <- filter(DE_KID_S1_vs_BLO_S1_Result, 
                 abs(logFC) > 3 & -log10(PValue) > 7)
# label_id = filter(DE_KID_S1_vs_BLO_S1_Result,
#                  id == 'HF01786')


##-------------------------------------------------------------------------


#创建画布
ggplot(
  data = DE_KID_S1_vs_BLO_S1_Result, aes(x = logFC, y = -log10(PValue))
) + 
  
  #改变画布主题
  theme_bw() +
  #改变主题属性
  theme(
    #改变标题属性
    plot.title = element_text(size = 18, hjust = 0.5), 
    #改变图例位置
    legend.position = c(0.08, 0.85), 
    #去除图例背景
    legend.background = element_blank()
    ) + 
  #改变图例属性
  ##去除多余图例
  guides(size = FALSE,
         alpha = FALSE) +

  
  
##-------------------------------------------------------------------------
  
  
  #添加散点图
  geom_point(
    
    #设置点的形状
    shape = 20, 
    aes(
      #映射颜色
      color = direction, 
      # #映射填充色到direction
      # fill = direction,
      #映射点的大小
      size = abs(logFC),
      #映射透明度
      alpha = -log10(PValue)
              )) +
   
  #添加阈值线条
  geom_hline(
    yintercept = -log10(0.05),
    linetype = 'dashed', 
    alpha = 0.5) +
  geom_vline(
    xintercept = c(0.5,-0.5), 
    linetype = 'dashed',
    alpha = 0.5) +
  
  #添加标签
  geom_label_repel(data = top_de, 
                   aes(label = id)) +
  
  
##-------------------------------------------------------------------------
  
  
  
  #自定义颜色范围
  ##ggsci改变颜色标度
  ##scale_color_aaas()
  scale_color_manual(values = my_palette) +
  
  #自定义点大小范围
  scale_size(range = c(0.1, 3)) +
  
  #自定义透明度范围
  scale_alpha(range = c(0.3, 1)) +
  
  #自定义坐标轴名称
  labs(x = 'log10 Fold Change',
       y = '-log10 Pvalue',
       title = 'DE Volcano Plot',
       size = '-log10 Pvalue',
       color = 'Direction') + 
  
  #自定义坐标轴范围
  ylim(c(0, 30)) +
  xlim(c(-6, 8))
  
  
#输出pdf
# dev.off()

```


```{r}

```
















