---
title: "RNAseq Clustering analysis"
output:
  html_document:
    df_print: paged
---
#1. Input Data: 

```{r Input Data}
#1. Input Data: 

gene_count <- read.table('~/Mithrandir.training/R.data/InputData/genes.counts.matrix', 
                       header = TRUE, row.names = 1)


gene_exp <- read.table('~/Mithrandir.training/R.data/InputData/genes.TMM.EXPR.matrix', 
                       header = TRUE, row.names = 1)


library(readr)
library(tidyverse)
gene_info <- read_delim("~/Mithrandir.training/R.data/InputData/query_seqs.fa.emapper.annotations",
                        delim = "\t", 
                        escape_double = FALSE, 
                        col_names = FALSE, 
                        comment = "#", 
                        trim_ws = TRUE)%>%
  select(Gene_Id = X1,
         Gene_Sumbol = X6,
         GO = X7,
         Ko = X9,
         Pathway = X10,
         COG = X21,
         Gene_Name = X22)


##~/Mithrandir.training/R.data/InputData/sample_info.txt
sample_info <- read.delim("~/Mithrandir.training/R.data/InputData/sample_info.txt", 
                          row.names=1)
```
#2. Sample correlation analysis

```{r Parson correlation coefficient analysis}
#2. Sample correlation analysis:

##Parson correlation coefficient
sample_cor <- round(cor(gene_exp), digits = 2)
library(pheatmap)
pheatmap(sample_cor)
```
#3. Sample clustering analysis

```{r calculate distance matrix}
##Transverse firstly
sample_dist <- dist(t(gene_exp))

##Clusting
sample_hc <- hclust(sample_dist)
plot(sample_hc)
```

#4. Save Data

```{r}
save(gene_count, 
     gene_exp, 
     sample_info, 
     gene_info, 
     file ='~/Mithrandir.training/R.data/OutputData/Inputdata.rdata')

save(sample_cor, 
     sample_hc, 
     sample_dist,
     file='~/Mithrandir.training/R.data/OutputData/Clustering.rdata')
```

